### ISSUE TITLE
Support for !global

### ISSUE THREAD

**Issue by zamith** [lacroixdesign/node-neat#10]
When updating to `1.4.2` I get an error in `node-neat/assets/stylesheets/grid/_private.scss:29`, saying it cannot read the values after `$columns`. 

This is working fine in `1.3.x`, I believe this has to do with libsass no being fully compliant with version `3.4` of Sass.

**Comment by josiahwiebe** [comment]
Just chiming in here — @iamlacroix, I'm having the same issue. You can view my source [here](https://github.com/collectifco/sotk/tree/form-validation).

**Comment by iamlacroix** [comment]
@josiahwiebe Thanks for linking your source, that helped a ton. After cloning and running `npm install`, version `0.14.2` of grunt-sass was installed on my machine. This exact version seems to [lock node-sass in at `0.9.3`](https://github.com/sindresorhus/grunt-sass/blob/10fdfce2eadbc8dd14cc07cf0ae4a6bb76249cf2/package.json#L35), and is strange because previous patch versions of `0.14.x` had a more relaxed target (and thus would include node-sass `0.9.6` when installed).

The particular version of node-sass that is installed includes an older version of Libsass, which throws an error when it encounters a `!global`. Updating grunt-sass to the latest release seems to fix the issue, as it includes a newer version of node-sass.

Update the grunt-sass line of your `package.json` file to the following and let me know if that fixes it:

```json
"grunt-sass": "^0.17.0",
```

**Comment by josiahwiebe** [comment]
@iamlacroix thanks! I had just figured that out right before I got this. Worked like a charm.

**Comment by zamith** [comment]
@iamlacroix That fixes my issue as well. Thanks for all the trouble. 

Thanks @josiahwiebe for the contribution.

I'm closing this now.
