### ISSUE TITLE
Eyeglass Module?

### ISSUE THREAD

**Issue by chriseppstein** [lacroixdesign/node-neat#18]
Eyeglass is a node-sass integration for sass modules like neat and bourbon. It's fairly trivial to make this module into an eyeglass module so that any eyeglass users need only add node-neat to their package.json and it will automatically be importable.

I will send a pull request for you.

**Comment by chriseppstein** [comment]
nevermind, I see that the official projects have node modules now so I will do the integration there.

**Comment by iamlacroix** [comment]
Oh, thank you anyways! I created this back when Bourbon and Neat didn't work with libSass unaltered, so these versions consisted of a bunch of changes to target that library.

Nowadays the original versions are compatible, so these simply existed for convenience. I plan on updating the README to recommend users install the official library once Bourbon 5.0 stable is released, since it will provide the `includePaths` property and this version will cease to have a purpose :)
